name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
#    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Decrypt db setting
        run: openssl enc -d -aes-256-ecb -md md5 -in ${{ secrets.DB_SECRET_FILE }} -out ${{ secrets.DB_CLEAN_FILE }} -k ${{ secrets.OSSL_KEY }}
      - name: Decrypt ggsheet
        run: openssl enc -d -aes-256-ecb -md md5 -in ${{ secrets.GGS_SECRET_FILE }} -out ${{ secrets.GGS_CLEAN_FILE }} -k ${{ secrets.OSSL_GGS_KEY }}
      - name: Clean project
        run: mvn clean
      - name: Update dependency
        run: mvn dependency:go-offline
      - name: Build jar
        run: mvn -B package --file pom.xml
      - name: Copy build file
        run: cp target/dropship-front-1.0.0.jar /root/workspace
      - name: Stop current service
        run: systemctl stop dropship.service
      - name: Start new service
        run: systemctl start dropship.service
